# -*- coding: utf-8 -*-
"""NLP_Simple_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKv7J-TWVR55ru4PjM-O0kve5QUpxBk0
"""

import nltk
nltk.download("punkt")
from nltk.tokenize import word_tokenize

"""Tokenization"""

text="Imran khan is a true leader of pakistan and he saved from a military dictatorship brutality"
nltk.download('punkt_tab')
tokens=word_tokenize(text)
print(tokens)

"""Lower casesing and stopword removal

"""

import nltk
# Corrected list comprehension for lowercasing tokens
lowercase_tokens = [token.lower() for token in tokens]

# Download stopwords (if not already downloaded)
#nltk.download('stopwords')
from nltk.corpus import stopwords
#from nltk.tokenize import word_tokenize
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
print(stop_words)
filtered_tokens = [w for w in tokens if w.lower() not in stop_words]
print(filtered_tokens)

"""Stemming and lemmetization

"""

from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

stemming=PorterStemmer()
lemmatizers=WordNetLemmatizer()
print(stemming.stem('studies'))
print(lemmatizers.lemmatize('studies'))

"""BOW AND TF-IDF"""

from sklearn.feature_extraction.text import CountVectorizer
x=["pakistan zindabad","Imran khan zindabad","asim muneer kutta","dil dil pakistan"]
vectorizers=CountVectorizer()
y=vectorizers.fit_transform(x)
print(vectorizers.get_feature_names_out())
print(y.toarray() )




from sklearn.feature_extraction.text import TfidfVectorizer
vectorize=TfidfVectorizer()
z=vectorize.fit_transform(x)
print(vectorize.get_feature_names_out())
print(z.toarray())

"""word and contextually embedding"""

!pip install gensim
from gensim.models import Word2Vec
sentence=[["Apple","is","fruit"],["Hassan","is","Lagent"]]
model=Word2Vec(sentence,vector_size=50,min_count=1)
print(model.wv['Apple'])